---
title: "First Pass DDS 1"
author: "Adam Canton"
date: "6/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(magrittr)
library(dplyr)
library(tidyr)
library(forcats)
library(matrixStats)
library(GGally)
library(caret)
library(corrplot)
library(cowplot)
library(ggExtra)
library(ggthemes)
library(maps)
library(naniar)
library(olsrr)
library(stringr)
library(e1071)
library(FNN)
library(MASS)
library(ggthemes)
library(caret)
library(e1071)
library(reshape2)
```

```{r}
# pulling datasets
Beers <- read.csv(file = "F:/R For Real/DDS Project 1/DDS-Project-1/Beers.csv")
Breweries <- read.csv(file = "F:/R For Real/DDS Project 1/DDS-Project-1/Breweries.csv")

# Merge Beer and Brewery
BeerBrewery = merge(Beers, Breweries, by.x = "Brewery_id", by.y = "Brew_ID")

# Change some column names for tidyness
names(BeerBrewery)[2] <- "Beer"
names(BeerBrewery)[8] <- "Brewery"
```

```{r}
head(BeerBrewery, 6)
tail(BeerBrewery, 6)
```

```{r}
gg_miss_var(BeerBrewery)
```

```{r}
na_count <- sapply(BeerBrewery, function(y) sum(length(which(is.na(y)))))
na_count <- data.frame(na_count)
na_count
```


```{r}
# Comments on missing Style Data:

## n(227) Cedar Creek Brewery Special Release - actually refers to 2 different beers Smoked Cherry Quad and Excelsior (Imperial Milk Stout) - https://www.cedarcreekbrewery.com/special-release-beers maybe average them out? ABV - 9.2 v 9.8,  IBU - 33 v 47, Average 9.5 and 40 

## n(455) Freetail Brewing Oktoberfiesta - Style is Marzen/Oktoberfest - https://www.freetailbrewing.com/our-brews/

## n(946) Four Peaks Kilt Lifter Scottish Ale -  Style is Amber Ale - https://www.beeradvocate.com/beer/profile/2171/6218/

## n(992) Oskar Blues The Crowler - Doesnt even seem like it is a beer type, just a resealable can. Consider getting rid of it

## n(993) Oskar Blues Can'D AID Foundation is in fact water... just canned like beer for hurricane recovery

```

```{r}
# Comments on 62 missing ABV Data -  most of this is likely recoverable - ## row | brewery | beer | ABV | IBU if avail

## 75 Brewery Vivant Fat Paczki - 7.5%
BeerBrewery$ABV[75] = 0.075
## 76 Brewery Vivant Earth-Like-Planets 5.5%
BeerBrewery$ABV[76] = 0.055
## 186 Sun King Brewing Company 30 Min Coma 4.5% abv - 65 IBU
BeerBrewery$ABV[186] = 0.045
BeerBrewery$IBU[186] = 65
## 193 Sun King Brewing Company Bourbon Barrel Cowbell 6% abv - 23 IBU
BeerBrewery$ABV[193] = 0.060
BeerBrewery$IBU[193] = 23
## 227 Cedar Creek Brewery Special Release commented above

## 252 James Page Brewing Company Bastian 6.2% no IBU
BeerBrewery$ABV[252] = 0.062
## 440 Crazy Mountain Brewing Company Winter Wondergrass Festival Ale 4.9% no IBU
BeerBrewery$ABV[440] = 0.049
## 441 Crazy Mountain Brewing Company Boohai Red Ale 6%
BeerBrewery$ABV[441] = 0.060
## 508 Blue Owl Brewing Professor Black 6.2%
BeerBrewery$ABV[508] = 0.062
## 509 Blue Owl Brewing Little Boss 3.8%  - 7 IBU
BeerBrewery$ABV[509] = 0.038
BeerBrewery$IBU[509] = 7
## 510 Blue Owl Brewing Van Dayum! 5.7%
BeerBrewery$ABV[510] = 0.057
## 511 Blue Owl Brewing Spirit Animal 5.5%
BeerBrewery$ABV[511] = 0.055
## 568 Keweenaw Brewing Company U. P. Witbier 5.5% No IBU
BeerBrewery$ABV[568] = 0.055
## 569 Keweenaw Brewing Company November Gale Pale Ale 5% - 5 IBU
BeerBrewery$ABV[569] = 0.050
BeerBrewery$ABV[569] = 5
## 570 Keweenaw Brewing Company Olde Ore Dock Scottish Ale 7%
BeerBrewery$ABV[570] = 0.070
## 571 Keweenaw Brewing Company Widow Maker Black Ale 5.2%
BeerBrewery$ABV[571] = 0.052
## 572 Keweenaw Brewing Company Lift Bridge Brown Ale 5%
BeerBrewery$ABV[572] = 0.050
## 573 Keweenaw Brewing Company Pick Axe Blonde Ale 4.9%
BeerBrewery$ABV[573] = 0.049
## 574 Keweenaw Brewing Company Red Jack Amber Ale 5.1%
BeerBrewery$ABV[574] = 0.051
## 629 West Sixth Brewing West Sixth IPA 7%
BeerBrewery$ABV[629] = 0.07
## 789 Weston Brewing Company Royal Lager Couldnt Find
## 791 Weston Brewing Company O'Malley's Stout 5.5%
BeerBrewery$ABV[791] = 0.055
## 793 Weston Brewing Company O'Malley's Cream Ale 0% ?
## 900 Fort Pitt Brewing Company Fort Pit Ale Couldnt find - not in production any longer
## 992 Oskar Blues Brewery The Crowler - not an actual beer
## 993 Oskar Blues Brewery Cand Aid - not an actual beer
## 994 Oskar Blues Brewery Icey P.A. 7% 
BeerBrewery$ABV[994] = 0.07
## 996 Oskar Blues Brewery Birth IPA couldnt find
## 1158 Capital Brewery Supper Club Lager 5.2% 
BeerBrewery$ABV[1158] = 0.075
## 1298 Rochester Mills Brewing Company Cal and Co Black Cherry Porter 7%
BeerBrewery$ABV[1298] = 0.07
## 1424 Ska Brewing Company Autumnal Mole' Stout 5.8%
BeerBrewery$ABV[1424] = 0.058
## 1480 Thunderhead Brewing Company Cornstalker Dark Wheat 5.2% 
BeerBrewery$ABV[1480] = 0.052
## 1631 Iron Hill Brewery & Restaurant Appreciation Ale 9.4%
BeerBrewery$ABV[1631] = 0.094
## 1887 Blue Blood Brewing Company Double Play Pilsner 5.2%
BeerBrewery$ABV[1887] = 0.052
## 1892 Blue Blood Brewing Company N Street Drive-In 50th Anniversary IPA 8.6%
BeerBrewery$ABV[1892] = 0.086
## 1919 Revolution Brewing Rye Porter No longer in production
## 1924 Revolution Brewing Miner's Gold 5.1%
BeerBrewery$ABV[1924] = 0.051
## 1951 Santa Fe Brewing Company Sante fe Oktoberfest 6%
BeerBrewery$ABV[1951] = 0.06
## 2096 MillKing It Productions AXL Pale Ale 5.2
BeerBrewery$ABV[2096] = 0.062
## 2177 Brindle Dog Brewing Company Tampa Pale Ale 6.2
BeerBrewery$ABV[2177] = 0.062
## 2178 Brindle Dog Brewing Company Orange Grove Wheat Ale - couldnt find
## 2184 Pete's Brewing Company Pete's Wicked Pale Ale (1997) 5.3
BeerBrewery$ABV[2184] = 0.053
## 2227 The Manhattan Brewing Company Manhattan Gold Lager (1990) 5.2 (Beer Authority NYC)
BeerBrewery$ABV[2227] = 0.052
## 2234 Dock Street Brewery Dock Street Amber Beer (1992) 5%
BeerBrewery$ABV[2234] = 0.05
## 2242 Devil's Canyon Brewery Kaleidoscope Collaboration (2012) 5.5
BeerBrewery$ABV[2242] = 0.055
## 2259 Cans Bar and Canteen THP White (2006) Closed
## 2260 Cans Bar and Canteen THP Amber (2006) Closed
## 2261 Cans Bar and Canteen THP Light (2006) Closed
## 2262 Cans Bar and Canteen THP Dark (2006) Closed
## 2296 Spilker Ales Hopluia (2004) 5.2
BeerBrewery$ABV[2296] = 0.052
## 2345 Buckbean Brewing Company Roler Bock 7.2
BeerBrewery$ABV[2345] = 0.072
## 2351 Dolores River Brewery Dolores River Hefeweizen No Info
## 2352 Dolores River Brewery Dolores River ESB 6.1
BeerBrewery$ABV[2352] = 0.061
## 2353 Dolores River Brewery Snaggletooth Double Pale Ale No Info 
## 2354 Dolores River Brewery Dolores River Pale Ale 5.8
BeerBrewery$ABV[2354] = 0.058
## 2355 Dolores River Brewery Dolores River Dry Stout No info
## 2356 Dolores River Brewery Dolores River Mild No info
## 2357 Flat Rock Brewing Company Inclined Plane Ale 4.2
BeerBrewery$ABV[2357] = 0.042
## 2365 Harvest Moon Brewing Company Great Falls Select Pale Ale 5
BeerBrewery$ABV[2365] = 0.05
## 2370 Grand Canyon Brewing Company Black Iron India Pale Ale 7.2
BeerBrewery$ABV[2370] = 0.072
## 2394 Prescott Brewing Company Ponderosa IPA 6.5 70
BeerBrewery$ABV[2394] = 0.065
BeerBrewery$ABV[2394] = 70
## 2395 Prescott Brewing Company Liquid Amber Ale 5 17
BeerBrewery$ABV[2395] = 0.050
BeerBrewery$IBU[2395] = 17

```

```{r}
# There are over 1,000 missing IBU observations - not sure how to deal with this many missing values. Likely going to have to automate something - Surely there is a beer api?
# Apparently lots of methods
## Have NA be a level
## use KNN or NB to impute from predicted values
```


```{r}
# Show number of breweries by state - needs some color
Breweries %>% group_by(State) %>% count_() %>% ggplot(aes(x = reorder(State, -n), y = n )) +
  geom_col() + theme(axis.text.x = element_text(angle = 90, vjust = -0.05)) +  xlab("State") + ylab('Number of Breweries') + 
  ggtitle("Number of Breweries by State") + geom_text(aes(label = n), vjust = -0.5, size = 3)
```


```{r}
Breweries %>% group_by(State) %>% count_()
```

```{r}
mapBreweries = Breweries %>% group_by(State) %>% count_()
```

```{r}
# Where do we get statepop? it keeps throwing an error up. 
mapBreweries$State = as.character(mapBreweries$State)
mapBreweries$State = sub(" ", "", mapBreweries$State)
map2 = merge(statepop, mapBreweries, by.x = "abbr", by.y = "State")
plot_usmap(data = map2, values = "n", color = "red", labels = TRUE, label_color = "white") + 
  scale_fill_continuous(name = "Brewery count", label = scales::comma) + 
  labs(title = "USA MAP", subtitle="Brewery counts by State") +
  theme(legend.position = "right")
```

```{r}
# adds a factorized version of IBU to the data set and displays the levels - 108 of them including NA
BeerBrewery$IBUFac = as.factor(BeerBrewery$IBU)
BeerBrewery$IBUFac = addNA(BeerBrewery$IBUFac)
levels(BeerBrewery$IBUFac)
```
```{r}
BeerBreweryNA.delete = BeerBrewery %>% filter(IBU != "NA")
```

```{r}
# Shows IBU with and Without the NA
BeerBrewery %>% group_by(IBUFac) %>% filter(IBU != "NA") %>% summarise(countibu = n()) %>% ggplot(aes(x = IBUFac, y = countibu)) +
  geom_col(width = 0.75) + xlab("IBU Factor") + ylab("# of Beers with this IBU") + theme(axis.text.x = element_text(angle = 90, vjust = -0.05))

BeerBrewery %>% group_by(IBUFac) %>% summarise(countibu = n()) %>% ggplot(aes(x = IBUFac, y = countibu)) +
  geom_col(width = 0.75) + xlab("IBU Factor") + ylab("# of Beers with this IBU") + theme(axis.text.x = element_text(angle = 90, vjust = -0.05))
```

```{r}
#Creates a style data frame
Styles <- BeerBrewery %>% group_by(Style) %>% summarise(CountStyle = n())
Styles %>% arrange(-CountStyle)
```

```{r}
Styles %>% arrange(-CountStyle) %>% slice(1:15) %>% ggplot(aes(x = reorder(Style, CountStyle), y = CountStyle)) + geom_col() +
  theme(axis.text.x = element_text(angle = 90, vjust = -0.05)) + ylab("Number of Beers") + xlab("Most Popular Styles") + coord_flip() + 
  ggtitle("15 Most Popular Beer Styles by Style Frequency")
```

```{r}
set.seed(4)
splitperc = 0.70
index<- sample(1:dim(BeerBreweryNA.delete)[1],round(splitperc*dim(BeerBreweryNA.delete)[1]),replace=F)
train<- BeerBreweryNA.delete[index,]
test<- BeerBreweryNA.delete[-index,]
```


# Linear Models 1-3
```{r}
# Very Simple
linearmodel1 <- lm(IBU ~ ABV, data = train)
summary(linearmodel1)
ols_plot_resid_fit(linearmodel1)
ols_plot_resid_lev(linearmodel1)
ols_plot_resid_qq(linearmodel1)
ols_plot_resid_hist(linearmodel1)
ols_plot_cooksd_bar(linearmodel1)
```

```{r}
# Pretty Complex
linearmodel2 <- lm(IBU ~ poly(log(ABV),3), data = train)
summary(linearmodel2)
ols_plot_resid_fit(linearmodel2)
ols_plot_resid_lev(linearmodel2)
ols_plot_resid_qq(linearmodel2)
ols_plot_resid_hist(linearmodel2)
ols_plot_cooksd_bar(linearmodel2)
```

```{r}
# Medium Complexity
linearmodel3 <- lm(IBU ~ poly(ABV,3), data = train)
summary(linearmodel3)
ols_plot_resid_fit(linearmodel3)
ols_plot_resid_lev(linearmodel3)
ols_plot_resid_qq(linearmodel3)
ols_plot_resid_hist(linearmodel3)
ols_plot_cooksd_bar(linearmodel3)
```

```{r}
BeerBreweryNA.delete %>% ggplot(aes(x = ABV, y = IBU)) + geom_point() + geom_smooth(formula = y~x) + xlim(0,0.15) + geom_jitter() + 
  ggtitle("Scatterplot of IBU v ABV")
```

```{r}
iterations = 500
splitperc = 0.70
# column building
LModelRMSE1 = c()
LModelRMSE2 = c()
LModelRMSE3 = c()

for(i in 1:iterations)
{
  set.seed(i)
  index<- sample(1:dim(BeerBreweryNA.delete)[1],round(splitperc*dim(BeerBreweryNA.delete)[1]),replace=F)
  train<- BeerBreweryNA.delete[index,]
  test<- BeerBreweryNA.delete[-index,]
  
  predictions1 <- linearmodel1 %>% predict(test)
  
  d1 = data.frame(R2 = R2(predictions1,test$IBU), RMSE = RMSE(predictions1,test$IBU), MAE = MAE(predictions1, test$IBU))
  LModelRMSE1 = c(LModelRMSE1,d1$RMSE)
  
  predictions2 <- linearmodel2 %>% predict(test)

  d2 = data.frame(R2 = R2(predictions2,test$IBU), RMSE = RMSE(predictions2,test$IBU), MAE = MAE(predictions2, test$IBU))
  LModelRMSE2 = c(LModelRMSE2, d2$RMSE)
  
  predictions3 <- linearmodel3 %>% predict(test)
  
  d3 = data.frame(R2 = R2(predictions3, test$IBU), RMSE = RMSE(predictions3, test$IBU), MAE = MAE(predictions3, test$IBU))
  
  LModelRMSE3 = c(LModelRMSE3, d3$RMSE)
  
  
}  
  
Linear.Model.Average.RMSE = cbind(LModelRMSE1, LModelRMSE2, LModelRMSE3)
linearRmsedf = as.data.frame(Linear.Model.Average.RMSE)
Means = colMeans(Linear.Model.Average.RMSE)
SDs = round(colSds(Linear.Model.Average.RMSE), 5)
range1 = max(linearRmsedf$LModelRMSE1) - min(linearRmsedf$LModelRMSE1)
range2 = max(linearRmsedf$LModelRMSE2) - min(linearRmsedf$LModelRMSE2)
range3 = max(linearRmsedf$LModelRMSE3) - min(linearRmsedf$LModelRMSE3)
linearRmsedf = melt(linearRmsedf)
  
  
  
# Looking at descriptive stats
Means
print("Standard Devs")
SDs
print("ranges - measure of variance between train/test shuffles")
print(paste("Model 1 Range" , round(range1, 5)))
print(paste("Model 2 Range" , round(range2, 5)))
print(paste("Model 3 Range" , round(range3, 5)))
cat("Summary: 
    ")
summary(Linear.Model.Average.RMSE)

# Scatter
Pred1 <- data.frame(Value = predictions1, Model = "Linear Model 1")
Pred2 <- data.frame(Value = predictions2, Model = "Linear Model 2")
Pred3 <- data.frame(Value = predictions3, Model = "Linear Model 3")
PredActual <- data.frame(ActualValue = test$IBU)
PredAll <- rbind(Pred1, Pred2, Pred3)
PredActual <- rbind(PredActual,PredActual, PredActual)
PredAll <- cbind(PredAll, PredActual)
PredAll %>% ggplot(aes(x = Value, y = ActualValue, fill = Model)) + geom_point(aes(color = Model)) + geom_smooth(formula = y~x)+
facet_wrap(facets = PredAll$Model) + ggtitle("Scatter Plot of Models") + xlab("Predicted") + ylab("Observed")

# Column
linearRmsedf %>% group_by(variable) %>% summarise(mean = (mean(value))) %>% 
  ggplot(aes(x = reorder(variable, -mean), y = mean, fill = variable)) + geom_col(width = 0.75) + geom_text(aes(label = round(mean,3), vjust = -0.5)) + 
  ggtitle("Average RMSE over 500 Shuffles (Linear Models)") + xlab("Model #") + ylab("Mean RMSE")

# Boxplot
linearRmsedf %>%  ggplot(aes(x = variable, y = value)) + geom_boxplot(aes(fill = variable)) + facet_wrap(~variable,ncol = TRUE) +
  ggtitle("Mean RMSE Distribution by Model") + ylab("Mean RMSE") + coord_flip() + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())
# Histogram
linearRmsedf %>%  ggplot(aes(x = value)) + geom_histogram(aes(fill = variable)) + facet_wrap(~variable,ncol = TRUE) +
  ggtitle("Mean RMSE Distribution by Model") + xlab("Mean RMSE") + 
  theme(axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank())

# Dont forget multiple comparison adjustment

t.test(LModelRMSE1,LModelRMSE2, var.equal = FALSE)
t.test(LModelRMSE1,LModelRMSE3, var.equal = FALSE)
t.test(LModelRMSE2,LModelRMSE3, var.equal = FALSE)
```
# NaiveBayes Prediction
```{r}
# predict(NBmodel, newdata, type = raw) / type = raw for probabilities
# naiveBayes(predictors, response, laplace)
NB.Model.1 <- naiveBayes(train[,c(2,4,6)], train$IBUFac)
table(predict(NB.Model.1,test[,c(2,4,6)]), test$IBUFac)
CM = confusionMatrix(table(predict(NB.Model.1,test[,c(2,4,6)]), test$IBU))
CM  
  #AccuracyAgg = c(AccuracyAgg, CM$overall[1])
  #SensitivityAgg = c(SensitivityAgg,CM$byClass[1] )
  #SpecificityAgg = c(SpecificityAgg,CM$byClass[2] )


```

